<?php

namespace App\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class TaskFilterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder -> setMethod('GET');
        $builder->add('isCompleted', ChoiceType::class, [
            'choices' => [
                'Yes' => true,
                'No' => false,
                'Every' => null,
            ],
            'label' => 'Completed'
        ])->add('submit', SubmitType::class, [
            'label' => 'Filtered'
        ]);

    }

}